config/routes.rb
Rails.application.routes.draw do
  resources :clients
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :client

  def client_name
    "#{client.first_name} #{client.last_name}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :accounts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def show
    @client = Client.find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
   @client = Client.new(client_attributes)

   if @client.save
     redirect_to @client
   else
     render 'new'
   end
  end
 
  def index
    @clients = Client.all
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])

    if @client.update_attributes(client_attributes)
      redirect_to @client, notice: 'This client was updated.'
    else
      render 'edit'
    end
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    
    redirect_to clients_path
  end

  private
 
  def client_attributes
    params.require(:client).permit(:first_name, :last_name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
  def client_name(client)
    "#{client.first_name} #{client.last_name}"
  end
end

app/views/clients/_form.html.erb
<%= form_for client do |f| %>
  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p><%= f.submit button_label %></p>
<% end %>

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/edit.html.erb
<h1>Edit <%= client_name(@client) %></h1>
<%= render 'form', client: @client, button_label: "Update client" %>

app/views/clients/index.html.erb
<h1>All Clients</h1>
<ul>
  <% @clients.each do |client| %>
   <li><%= link_to client_name(client), client %></li>
  <% end %>
</ul>

<p><%= link_to 'New Client', new_client_path %></p>

app/views/clients/new.html.erb
<h1>Create a new client</h1>
<%= render 'form', client: @client, button_label: "Create client" %>

app/views/clients/show.html.erb
<h1><%= client_name(@client) %></h1>

<p>Email: <%= mail_to @client.email %></p>

<% if @client.accounts.empty? %>
  <p>You have no accounts, fool! Open one!</p>
<% else %>
  <ul>
    <% @client.accounts.each do |account| %>
      <li><%= account.name %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "Edit #{client_name(@client)}", edit_client_path(@client) %>
<%= link_to "Delete #{client_name(@client)}", client_path(@client), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AccountManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>